# -*- coding: utf-8 -*-
"""Assignment_15_a_MDIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14gaYL4ggoLilcXqrr1gbvM4I_ghVG1pA
"""

from google.colab import drive
!ls

drive.mount('/content/drive')

cd '/content/drive/MyDrive/MiDaS-master'

!python run.py